import postgres from "postgres";

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) throw new Error("DATABASE_URL not set");

const sql = postgres(DATABASE_URL);

const resolucoes = [
  // === MEDICAMENTOS ===
  { numero_re: "RE nº 3.001/2020", data_publicacao: "2020-02-14", data_vigencia_inicio: "2020-02-14", status: "revogada", tipo_produto: "medicamentos", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Ibuprofeno 600mg Comprimidos Revestidos", principio_ativo: "Ibuprofeno", fabricante_nome: "EMS S.A.", fabricante_cnpj: "57.507.378/0001-01", numero_registro_anvisa: "1.0800.0004.004-1", ementa: "Suspende a comercialização e distribuição do ibuprofeno 600mg comprimidos, lote 190234A, por reprovação no teste de dissolução (Q<75%). RE revogada após regularização comprovada pelo fabricante.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.102/2020", data_publicacao: "2020-04-08", data_vigencia_inicio: "2020-04-08", status: "revogada", tipo_produto: "medicamentos", tipo_acao: ["comercializacao"], nome_produto: "Cloroquina 150mg Comprimidos", principio_ativo: "Cloroquina difosfato", fabricante_nome: "Farmanguinhos - Fiocruz", fabricante_cnpj: "03.017.462/0002-99", numero_registro_anvisa: "1.0800.0005.005-2", ementa: "Suspende temporariamente a comercialização da Cloroquina 150mg por desvio de identidade (teor fora da especificação 95-105%). RE revogada após inspeção e revalidação analítica dos lotes afetados.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.247/2020", data_publicacao: "2020-06-22", data_vigencia_inicio: "2020-06-22", status: "revogada", tipo_produto: "medicamentos", tipo_acao: ["importacao", "comercializacao"], nome_produto: "Dexametasona 4mg/mL Solução Injetável", principio_ativo: "Dexametasona fosfato dissódico", fabricante_nome: "Hypofarma Instituto de Hypodermia e Farmácia Ltda", fabricante_cnpj: "25.436.999/0001-55", numero_registro_anvisa: "1.0800.0006.006-3", ementa: "Suspende a importação e comercialização da dexametasona 4mg/mL solução injetável por suspeita de contaminação por pirogênio acima do limite USP <85>.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.389/2021", data_publicacao: "2021-01-19", data_vigencia_inicio: "2021-01-19", status: "revogada", tipo_produto: "medicamentos", tipo_acao: ["comercializacao", "distribuicao", "uso"], nome_produto: "Azitromicina 500mg Comprimidos Revestidos", principio_ativo: "Azitromicina di-hidratada", fabricante_nome: "Medley Farmacêutica Ltda", fabricante_cnpj: "02.921.220/0001-02", numero_registro_anvisa: "1.0800.0007.007-4", ementa: "Suspende a comercialização, distribuição e uso da azitromicina 500mg, lotes 2020C a 2020F, por reprovação no teste de pureza (impurezas acima do limite ICH Q3A). RE revogada após destruição dos lotes.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.501/2021", data_publicacao: "2021-04-07", data_vigencia_inicio: "2021-04-07", status: "revogada", tipo_produto: "medicamentos", tipo_acao: ["fabricacao", "comercializacao"], nome_produto: "Metformina 500mg Comprimidos", principio_ativo: "Cloridrato de metformina", fabricante_nome: "Prati-Donaduzzi & Cia Ltda", fabricante_cnpj: "76.256.661/0001-87", numero_registro_anvisa: "1.0800.0008.008-5", ementa: "Suspende a fabricação e comercialização da metformina 500mg por detecção de NDMA (N-nitrosodimetilamina) acima do limite aceitável de 0,32 ppm, conforme Nota Técnica ANVISA nº 4/2021.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.622/2021", data_publicacao: "2021-07-14", data_vigencia_inicio: "2021-07-14", status: "revogada", tipo_produto: "medicamentos", tipo_acao: ["comercializacao", "recolhimento"], nome_produto: "Atenolol 50mg Comprimidos", principio_ativo: "Atenolol", fabricante_nome: "União Química Farmacêutica Nacional S.A.", fabricante_cnpj: "60.665.981/0001-74", numero_registro_anvisa: "1.0800.0009.009-6", ementa: "Suspende a comercialização e determina o recolhimento do atenolol 50mg, lote UQ2021B, por presença de partículas visíveis (vidro) na embalagem primária identificada em pós-comercialização.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.744/2021", data_publicacao: "2021-09-30", data_vigencia_inicio: "2021-09-30", status: "vigente", tipo_produto: "medicamentos", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Sitagliptina/Metformina 50mg+1000mg Comprimidos", principio_ativo: "Sitagliptina fosfato mono-hidratada; Cloridrato de metformina", fabricante_nome: "MSD Brasil Ltda", fabricante_cnpj: "56.991.441/0001-03", numero_registro_anvisa: "1.0800.0010.010-7", ementa: "Suspende a comercialização e distribuição do medicamento Sitagliptina/Metformina 50mg+1000mg por desvio de qualidade no teor de sitagliptina (fora da faixa 90-110%), detectado em análise fiscal de pós-comercialização.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.856/2022", data_publicacao: "2022-02-03", data_vigencia_inicio: "2022-02-03", status: "vigente", tipo_produto: "medicamentos", tipo_acao: ["comercializacao", "recolhimento"], nome_produto: "Varfarina Sódica 5mg Comprimidos", principio_ativo: "Varfarina sódica", fabricante_nome: "Farmavita Ltda", fabricante_cnpj: "05.192.227/0001-11", numero_registro_anvisa: "1.0800.0011.011-8", ementa: "Suspende a comercialização e determina recolhimento urgente da varfarina sódica 5mg, todos os lotes fabricados entre jan/2021 e dez/2021, por erro de dosagem (produto com 10mg ao invés de 5mg por comprimido). Risco à vida.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.970/2022", data_publicacao: "2022-05-18", data_vigencia_inicio: "2022-05-18", status: "vigente", tipo_produto: "medicamentos", tipo_acao: ["importacao", "comercializacao", "distribuicao"], nome_produto: "Semaglutida 0,25mg/dose Solução Injetável (Ozempic)", principio_ativo: "Semaglutida", fabricante_nome: "Novo Nordisk Farmacêutica do Brasil Ltda", fabricante_cnpj: "73.375.751/0001-04", numero_registro_anvisa: "1.0800.0012.012-9", ementa: "Suspende a importação, comercialização e distribuição de lotes específicos de semaglutida 0,25mg/dose por desvio nas canetas injetáveis (mecanismo de dosagem com falha de funcionamento identificada em campo). Alerta de segurança internacional.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.088/2022", data_publicacao: "2022-08-11", data_vigencia_inicio: "2022-08-11", status: "vigente", tipo_produto: "medicamentos", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Rivaroxabana 15mg Comprimidos Revestidos", principio_ativo: "Rivaroxabana", fabricante_nome: "Bayer S.A.", fabricante_cnpj: "18.459.628/0001-15", numero_registro_anvisa: "1.0800.0013.013-0", ementa: "Suspende a comercialização e distribuição de lotes de rivaroxabana 15mg (lotes BY2022-01 a BY2022-04) por falha na embalagem blister com potencial de permitir entrada de umidade, comprometendo a estabilidade do produto.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.201/2022", data_publicacao: "2022-11-24", data_vigencia_inicio: "2022-11-24", status: "revogada", tipo_produto: "medicamentos", tipo_acao: ["comercializacao"], nome_produto: "Esomeprazol 40mg Cápsulas de Liberação Prolongada", principio_ativo: "Esomeprazol magnésio tri-hidratado", fabricante_nome: "Astrazeneca do Brasil Ltda", fabricante_cnpj: "60.318.797/0001-07", ementa: "Suspende a comercialização das cápsulas de esomeprazol 40mg (lote AZ2022C) por reprovação no perfil de dissolução em pH 6,8, indicando liberação prematura do princípio ativo. RE revogada após substituição do lote.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.315/2023", data_publicacao: "2023-03-07", data_vigencia_inicio: "2023-03-07", status: "vigente", tipo_produto: "medicamentos", tipo_acao: ["fabricacao", "importacao"], nome_produto: "Valsartana 160mg Comprimidos Revestidos por Película", principio_ativo: "Valsartana", fabricante_nome: "Novartis Biociências S.A.", fabricante_cnpj: "56.994.502/0001-30", ementa: "Suspende a fabricação e importação de lotes de valsartana 160mg por detecção de NDEA (N-nitrosodietilamina) acima do limite interim de 0,083 ppm estabelecido pela ANVISA, em alinhamento com EMA e FDA.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.455/2023", data_publicacao: "2023-06-20", data_vigencia_inicio: "2023-06-20", status: "vigente", tipo_produto: "medicamentos", tipo_acao: ["comercializacao", "recolhimento"], nome_produto: "Amiodarona 200mg Comprimidos", principio_ativo: "Cloridrato de amiodarona", fabricante_nome: "Cristália Produtos Químicos Farmacêuticos Ltda", fabricante_cnpj: "44.734.671/0001-51", ementa: "Suspende a comercialização e determina recolhimento da amiodarona 200mg, lotes CR2023A e CR2023B, por contaminação microbiológica (presença de Escherichia coli além dos limites farmacopeicos) detectada em análise fiscal.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.589/2023", data_publicacao: "2023-09-12", data_vigencia_inicio: "2023-09-12", status: "vigente", tipo_produto: "medicamentos", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Ivermectina 6mg Comprimidos", principio_ativo: "Ivermectina", fabricante_nome: "Vitamedic Indústria Farmacêutica Ltda", fabricante_cnpj: "02.584.424/0001-18", ementa: "Suspende a comercialização e distribuição da ivermectina 6mg por alegações terapêuticas não autorizadas e rotulagem irregular, incluindo indicações off-label não aprovadas pela ANVISA para tratamento de doenças virais.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.672/2023", data_publicacao: "2023-11-28", data_vigencia_inicio: "2023-11-28", status: "vigente", tipo_produto: "medicamentos", tipo_acao: ["importacao", "comercializacao"], nome_produto: "Ozempic 1mg/dose (Semaglutida) Caneta Injetável", principio_ativo: "Semaglutida", fabricante_nome: "Novo Nordisk Farmacêutica do Brasil Ltda", fabricante_cnpj: "73.375.751/0001-04", ementa: "Suspende importação e comercialização de lote específico de Ozempic 1mg/dose por suspeita de falsificação identificada no mercado brasileiro. Produto suspeito apresenta hologramas e número de série divergentes dos registros do fabricante.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.780/2024", data_publicacao: "2024-01-23", data_vigencia_inicio: "2024-01-23", status: "vigente", tipo_produto: "medicamentos", tipo_acao: ["comercializacao", "distribuicao", "recolhimento"], nome_produto: "Montelucaste Sódico 5mg Comprimidos Mastigáveis", principio_ativo: "Montelucaste sódico", fabricante_nome: "Eurofarma Laboratórios S.A.", fabricante_cnpj: "92.939.410/0001-13", numero_registro_anvisa: "1.0800.0019.019-6", ementa: "Suspende comercialização, distribuição e determina recolhimento de lotes de montelucaste 5mg comprimidos mastigáveis (lotes EF2023-K, EF2023-L) por partículas metálicas (<0,5mm) detectadas após investigação de reclamação pós-mercado.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.999/2024", data_publicacao: "2024-06-18", data_vigencia_inicio: "2024-06-18", status: "vigente", tipo_produto: "medicamentos", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Liraglutida 1,8mg Solução Injetável Caneta 3mL (Victoza)", principio_ativo: "Liraglutida", fabricante_nome: "Novo Nordisk Farmacêutica do Brasil Ltda", fabricante_cnpj: "73.375.751/0001-04", numero_registro_anvisa: "1.0800.0020.020-7", ementa: "Suspende comercialização e distribuição de lotes de Victoza liraglutida 1,8mg por suspeita de produto falsificado sem número de lote válido nos registros do fabricante, identificado em farmácias do estado de SP.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 5.219/2025", data_publicacao: "2025-01-08", data_vigencia_inicio: "2025-01-08", status: "vigente", tipo_produto: "medicamentos", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Rosuvastatina Cálcica 20mg Comprimidos Revestidos", principio_ativo: "Rosuvastatina cálcica", fabricante_nome: "Aché Laboratórios Farmacêuticos S.A.", fabricante_cnpj: "60.659.463/0001-91", numero_registro_anvisa: "1.0800.0021.021-8", ementa: "Suspende comercialização e distribuição de rosuvastatina 20mg (lotes AC2024-P, AC2024-Q, AC2024-R) por desvio de qualidade na dureza dos comprimidos (abaixo do especificado), com risco de fragmentação prematura e impacto na dissolução.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 5.352/2025", data_publicacao: "2025-04-10", data_vigencia_inicio: "2025-04-10", status: "em_analise", tipo_produto: "medicamentos", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Comprimidos de Melatonina 10mg Manipulados", principio_ativo: "Melatonina", fabricante_nome: "FarmaCustom Manipulação Personalizada Ltda", fabricante_cnpj: "35.456.789/0001-90", ementa: "RE em análise: investigação em curso sobre comercialização de melatonina 10mg manipulada acima do limite de 0,21mg/dose estabelecido pela RDC nº 1.011/2024 para suplemento alimentar, sem enquadramento como medicamento com registro.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.856/2023", data_publicacao: "2023-01-10", data_vigencia_inicio: "2023-01-10", status: "revogada", tipo_produto: "medicamentos", tipo_acao: ["comercializacao"], nome_produto: "Dipirona Sódica 500mg/mL Solução Injetável 2mL", principio_ativo: "Metamizol sódico mono-hidratado", fabricante_nome: "Cristália Produtos Químicos Farmacêuticos Ltda", fabricante_cnpj: "44.734.671/0001-51", ementa: "Suspende comercialização da dipirona sódica solução injetável 500mg/mL, lote CR2022-Z, por presença de precipitado visível detectado na inspeção visual. RE revogada após conclusão do recolhimento voluntário.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.100/2022", data_publicacao: "2022-08-30", data_vigencia_inicio: "2022-08-30", status: "vigente", tipo_produto: "medicamentos", tipo_acao: ["fabricacao", "comercializacao", "distribuicao"], nome_produto: "Omeprazol 20mg Cápsulas Gelatinosas Duras", principio_ativo: "Omeprazol", fabricante_nome: "Legrand Pharma Indústria Farmacêutica Ltda", fabricante_cnpj: "85.685.937/0001-59", ementa: "Suspende fabricação, comercialização e distribuição de omeprazol 20mg por laudo do INCQS indicando micropartículas plásticas na formulação, oriundas de equipamento de produção com desgaste de componentes. Investigação em andamento.", link_documento_oficial: "https://www.in.gov.br/web/dou" },

  // === COSMÉTICOS ===
  { numero_re: "RE nº 3.050/2020", data_publicacao: "2020-03-03", data_vigencia_inicio: "2020-03-03", status: "revogada", tipo_produto: "cosmeticos", tipo_acao: ["comercializacao", "importacao"], nome_produto: "Batom Matte Importado Cor Cereja 3,5g", fabricante_nome: "Cosmetics International LLC", ementa: "Suspende a comercialização e importação de linha de batons importados por presença de chumbo acima de 20 ppm (limite ANVISA), conforme análise do INCQS. RE revogada após revisão da fórmula.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.215/2020", data_publicacao: "2020-07-21", data_vigencia_inicio: "2020-07-21", status: "revogada", tipo_produto: "cosmeticos", tipo_acao: ["comercializacao"], nome_produto: "Creme Clareador Facial com Hidroquinona 2% 30g", fabricante_nome: "Dermocare Cosméticos Ltda", fabricante_cnpj: "12.987.654/0001-32", ementa: "Suspende a comercialização de creme clareador facial por conter hidroquinona em concentração superior ao limite de 2% permitido para cosméticos grau 2, exigindo prescrição médica e reclassificação como produto de uso restrito.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.441/2021", data_publicacao: "2021-02-16", data_vigencia_inicio: "2021-02-16", status: "vigente", tipo_produto: "cosmeticos", tipo_acao: ["comercializacao", "importacao", "distribuicao"], nome_produto: "Protetor Solar FPS 30 Spray Corporal 200ml", fabricante_nome: "Sun & Care Importadora Ltda", fabricante_cnpj: "33.556.677/0001-88", ementa: "Suspende a comercialização, importação e distribuição de linha de protetores solares spray por FPS declarado de 30 verificado como inferior a 10 em análise fiscal, configurando propaganda enganosa e risco ao consumidor.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.613/2021", data_publicacao: "2021-06-09", data_vigencia_inicio: "2021-06-09", status: "vigente", tipo_produto: "cosmeticos", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Tinta para Cabelo Castanho Escuro Kit Completo", fabricante_nome: "Colorama Cosméticos S.A.", fabricante_cnpj: "45.678.901/0001-23", ementa: "Suspende a comercialização e distribuição de kit de tinta para cabelo por presença de p-fenilenediamina (PPD) em concentração de 8%, acima do limite máximo de 6% estabelecido na RDC nº 7/2015.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.799/2022", data_publicacao: "2022-01-25", data_vigencia_inicio: "2022-01-25", status: "vigente", tipo_produto: "cosmeticos", tipo_acao: ["comercializacao", "importacao"], nome_produto: "Sérum Facial Anti-idade com Retinol 1% 30ml", fabricante_nome: "Glow Skin Importações Ltda", fabricante_cnpj: "78.901.234/0001-56", ementa: "Suspende a comercialização e importação de sérum facial com retinol 1% por ausência de notificação ANVISA para cosmético grau 2 e alegações de eficácia medicamentosa não comprovadas (redução de rugas em 90 dias).", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.033/2022", data_publicacao: "2022-07-05", data_vigencia_inicio: "2022-07-05", status: "vigente", tipo_produto: "cosmeticos", tipo_acao: ["comercializacao", "recolhimento"], nome_produto: "Creme Esfoliante Corporal com AHA 10% 250g", fabricante_nome: "BioEssence Dermocosmética Ltda", fabricante_cnpj: "91.234.567/0001-78", ementa: "Suspende a comercialização e determina recolhimento de creme esfoliante com ácidos alfa-hidroxi (AHA) a 10% por ausência de alerta de fotossensibilidade na rotulagem, conforme exigido pela RDC nº 530/2021.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.178/2022", data_publicacao: "2022-10-19", data_vigencia_inicio: "2022-10-19", status: "vigente", tipo_produto: "cosmeticos", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Perfume Importado Masculino Eau de Parfum 100ml", fabricante_nome: "Fragrance Europe GmbH", fabricante_cnpj: "22.333.444/0001-55", ementa: "Suspende a comercialização e distribuição de perfume masculino importado por contaminação microbiológica (Pseudomonas aeruginosa) detectada em análise do INCQS. Lote PE-2022-EUR identificado.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.342/2023", data_publicacao: "2023-04-17", data_vigencia_inicio: "2023-04-17", status: "vigente", tipo_produto: "cosmeticos", tipo_acao: ["comercializacao", "importacao"], nome_produto: "Desodorante Antitranspirante Aerossol 150ml Importado", fabricante_nome: "Global Deodorant Corp (importador: BrasilBeauty Ltda)", fabricante_cnpj: "55.666.777/0001-99", ementa: "Suspende a comercialização e importação de desodorante antitranspirante aerossol por presença de benzeno como impureza acima de 1 ppm, substância cancerígena de classe 1 segundo IARC.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.489/2023", data_publicacao: "2023-07-31", data_vigencia_inicio: "2023-07-31", status: "vigente", tipo_produto: "cosmeticos", tipo_acao: ["comercializacao"], nome_produto: "Shampoo Anticaspa 2 em 1 com Piritionato de Zinco 250ml", fabricante_nome: "HairCare Brasil Comércio e Importação Ltda", fabricante_cnpj: "67.788.899/0001-11", ementa: "Suspende a comercialização de shampoo anticaspa por piritionato de zinco em concentração superior a 1,5% (encontrada 2,8%) e ausência de registro ANVISA para produto com ação medicamentosa.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.821/2024", data_publicacao: "2024-02-20", data_vigencia_inicio: "2024-02-20", status: "vigente", tipo_produto: "cosmeticos", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Tônico Facial Niacinamida 10% + Zinco 1% 30mL", fabricante_nome: "Skinceuticals Brasil Ltda", fabricante_cnpj: "46.781.084/0002-89", ementa: "Suspende comercialização e distribuição de tônico facial por alegação de 'poro minimizado em 100%' sem comprovação clínica, configurando propaganda enganosa (RDC nº 574/2021) e pH abaixo de 3,0 sem alertas de segurança.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 5.131/2024", data_publicacao: "2024-10-15", data_vigencia_inicio: "2024-10-15", status: "vigente", tipo_produto: "cosmeticos", tipo_acao: ["comercializacao", "importacao"], nome_produto: "Base Líquida Full Coverage com SPF 50 30mL Importada", fabricante_nome: "Fenty Beauty LLC (importador: LuxuryBeauty BR Ltda)", fabricante_cnpj: "02.123.456/0001-34", ementa: "Suspende comercialização e importação de base líquida com SPF 50 por FPS verificado como 22 em análise fiscal (declarado 50), ausência de notificação ANVISA como cosmético com proteção solar e sem os testes de fotoproteção exigidos.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.900/2022", data_publicacao: "2022-04-19", data_vigencia_inicio: "2022-04-19", status: "vigente", tipo_produto: "cosmeticos", tipo_acao: ["importacao", "comercializacao", "distribuicao"], nome_produto: "Creme Dental Clareador com Carvão Ativado 90g", fabricante_nome: "WhiteSmile Natural Products Co. (importador: SmileBR Ltda)", fabricante_cnpj: "13.234.567/0001-67", ementa: "Suspende importação, comercialização e distribuição de creme dental com carvão ativado por abrasividade (RDA) de 210 unidades, acima do limite de 250 unidades — produto próximo ao limite máximo seguro e sem comprovação de segurança para uso diário.", link_documento_oficial: "https://www.in.gov.br/web/dou" },

  // === ALIMENTOS ===
  { numero_re: "RE nº 3.078/2020", data_publicacao: "2020-03-30", data_vigencia_inicio: "2020-03-30", status: "revogada", tipo_produto: "alimentos", tipo_acao: ["comercializacao", "recolhimento"], nome_produto: "Leite em Pó Integral Modificado para Lactentes 400g", fabricante_nome: "Danone Nutricia Ltda", fabricante_cnpj: "61.099.834/0001-00", ementa: "Suspende a comercialização e determina recolhimento de lote de leite em pó para lactentes por presença de corpo estranho (fragmento metálico) detectado em rastreamento de qualidade interno. Lote LI20-0A identificado. RE revogada após conclusão do recolhimento.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.188/2020", data_publicacao: "2020-05-12", data_vigencia_inicio: "2020-05-12", status: "revogada", tipo_produto: "alimentos", tipo_acao: ["importacao", "comercializacao"], nome_produto: "Salmão Norueguês Defumado Fatiado a Vácuo 200g", fabricante_nome: "Nordic Fish AS (importador: Aqua Import Ltda)", fabricante_cnpj: "88.999.000/0001-22", ementa: "Suspende a importação e comercialização de lote de salmão defumado norueguês por detecção de Listeria monocytogenes acima dos limites permitidos (<100 UFC/g), com potencial risco para gestantes e imunodeprimidos.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.366/2021", data_publicacao: "2021-01-05", data_vigencia_inicio: "2021-01-05", status: "revogada", tipo_produto: "alimentos", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Whey Protein Concentrado 900g Sabor Baunilha", fabricante_nome: "Growth Supplements Indústria Ltda", fabricante_cnpj: "11.222.333/0001-44", ementa: "Suspende a comercialização e distribuição de whey protein concentrado por alegação de composição proteica de 80g/dose não comprovada (encontrado 52g/dose) e ausência de notificação ANVISA atualizada.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.534/2021", data_publicacao: "2021-05-24", data_vigencia_inicio: "2021-05-24", status: "vigente", tipo_produto: "alimentos", tipo_acao: ["importacao", "comercializacao", "distribuicao"], nome_produto: "Leite de Aveia Orgânico Bebida Vegetal 1L", fabricante_nome: "Oatly AB (importador: NaturalLife Distribuidora Ltda)", fabricante_cnpj: "23.334.445/0001-67", ementa: "Suspende a importação, comercialização e distribuição de bebida vegetal de aveia orgânica por ausência de registro e rotulagem com alegações nutricionais não autorizadas como alimento para fins especiais.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.721/2021", data_publicacao: "2021-09-14", data_vigencia_inicio: "2021-09-14", status: "vigente", tipo_produto: "alimentos", tipo_acao: ["comercializacao", "recolhimento"], nome_produto: "Amendoim Torrado Salgado 500g Linha Premium", fabricante_nome: "Amendoim Brasil Indústria e Comércio Ltda", fabricante_cnpj: "34.445.556/0001-89", ementa: "Suspende a comercialização e determina recolhimento de lote de amendoim torrado salgado por presença de aflatoxinas (B1+B2+G1+G2) acima do limite máximo de 20 µg/kg estabelecido pela RDC nº 7/2011.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.889/2022", data_publicacao: "2022-03-08", data_vigencia_inicio: "2022-03-08", status: "vigente", tipo_produto: "alimentos", tipo_acao: ["importacao", "comercializacao"], nome_produto: "Óleo de Palma Orgânico Extra Virgem 500ml Importado", fabricante_nome: "Green Palm Exports Ltd (importador: OrganiStore Ltda)", fabricante_cnpj: "45.556.667/0001-01", ementa: "Suspende a importação e comercialização de óleo de palma importado por ausência de comprovação de sustentabilidade certificada (RSPO) e rotulagem com termos 'extra virgem' e 'orgânico' sem certificação válida no Brasil.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.067/2022", data_publicacao: "2022-07-26", data_vigencia_inicio: "2022-07-26", status: "vigente", tipo_produto: "alimentos", tipo_acao: ["comercializacao", "distribuicao", "recolhimento"], nome_produto: "Granola Premium com Frutas Secas e Mel 500g", fabricante_nome: "Naturali Alimentos Saudáveis Ltda", fabricante_cnpj: "56.667.778/0001-23", ementa: "Suspende a comercialização, distribuição e determina recolhimento de granola premium por alegação de 'zero açúcar' na rotulagem em produto que contém 12g de açúcar por porção, configurando propaganda enganosa (CDC art. 37).", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.228/2023", data_publicacao: "2023-01-31", data_vigencia_inicio: "2023-01-31", status: "vigente", tipo_produto: "alimentos", tipo_acao: ["importacao", "comercializacao"], nome_produto: "Suplemento de Vitamina D3 10.000 UI Cápsulas Softgel", fabricante_nome: "VitaSupp International Inc (importador: HealthBrasil Ltda)", fabricante_cnpj: "67.778.889/0001-45", ementa: "Suspende a importação e comercialização de suplemento de vitamina D3 10.000 UI por concentração por porção acima do limite máximo permitido para suplemento alimentar (2.500 UI/dia) e ausência de registro ANVISA.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.406/2023", data_publicacao: "2023-06-05", data_vigencia_inicio: "2023-06-05", status: "vigente", tipo_produto: "alimentos", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Bebida Energética com Taurina e Guaraná 473ml Lata", fabricante_nome: "Energy Rush Bebidas Ltda", fabricante_cnpj: "78.889.990/0001-67", ementa: "Suspende a comercialização e distribuição de bebida energética por teor de cafeína superior a 35mg/100ml (encontrado 68mg/100ml) e ausência de advertências obrigatórias no rótulo conforme RDC nº 273/2005.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.912/2024", data_publicacao: "2024-04-09", data_vigencia_inicio: "2024-04-09", status: "vigente", tipo_produto: "alimentos", tipo_acao: ["importacao", "comercializacao", "distribuicao"], nome_produto: "Cacau em Pó Alcalino Orgânico 200g Importado", fabricante_nome: "Callebaut NV (importador: ChocoImport Ltda)", fabricante_cnpj: "68.789.012/0001-56", ementa: "Suspende importação, comercialização e distribuição de cacau em pó orgânico por níveis de cádmio de 1,2 mg/kg acima do limite de 0,6 mg/kg (regulamento europeu adotado pela ANVISA/MAPA), com potencial de acúmulo tóxico ao rim.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 5.264/2025", data_publicacao: "2025-02-18", data_vigencia_inicio: "2025-02-18", status: "vigente", tipo_produto: "alimentos", tipo_acao: ["comercializacao", "distribuicao", "recolhimento"], nome_produto: "Atum em Lata ao Óleo de Oliva 170g", fabricante_nome: "Coqueiro Gomes Costa S.A.", fabricante_cnpj: "03.853.896/0001-40", ementa: "Suspende comercialização, distribuição e determina recolhimento de lotes de atum em lata por contaminação com histamina acima de 100 mg/kg (limite RDC nº 724/2022: 100 mg/kg), detectada em monitoramento de qualidade pós-colheita.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.750/2021", data_publicacao: "2021-10-12", data_vigencia_inicio: "2021-10-12", status: "encerrada", tipo_produto: "alimentos", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Farinha de Trigo Especial Tipo 1 5kg", fabricante_nome: "Moinho Anaconda S.A.", fabricante_cnpj: "59.121.435/0001-92", ementa: "Suspende comercialização e distribuição de farinha de trigo tipo 1 por ausência de adição de ferro e ácido fólico nas proporções obrigatórias (RDC nº 150/2017) e rotulagem nutricional divergente. RE encerrada após reconstituição e regularização da linha.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.560/2023", data_publicacao: "2023-08-22", data_vigencia_inicio: "2023-08-22", status: "vigente", tipo_produto: "alimentos", tipo_acao: ["importacao", "comercializacao"], nome_produto: "Azeite de Oliva Extra Virgem DOP Importado 500ml", fabricante_nome: "Deoleo S.A. (importador: OliveSelect Brasil Ltda)", fabricante_cnpj: "79.890.123/0001-23", ementa: "Suspende importação e comercialização de azeite de oliva extra virgem com DOP (Denominação de Origem Protegida) por acidez livre de 0,9% (acima do limite de 0,8% para extra virgem) e perfil de ácidos graxos não compatível com a região de origem declarada.", link_documento_oficial: "https://www.in.gov.br/web/dou" },

  // === SANEANTES ===
  { numero_re: "RE nº 3.130/2020", data_publicacao: "2020-04-17", data_vigencia_inicio: "2020-04-17", status: "revogada", tipo_produto: "saneantes", tipo_acao: ["comercializacao", "importacao"], nome_produto: "Álcool em Gel 70% Antisséptico 500g", fabricante_nome: "CleanMax Produtos de Higiene Ltda", fabricante_cnpj: "89.990.001/0001-89", ementa: "Suspende a comercialização e importação de álcool em gel 70% por teor alcoólico real de 42% (fora da faixa 54-80%) e ausência de eficácia antimicrobiana comprovada, constituindo produto irregular durante emergência sanitária. RE revogada após término do estoque.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.296/2020", data_publicacao: "2020-08-04", data_vigencia_inicio: "2020-08-04", status: "revogada", tipo_produto: "saneantes", tipo_acao: ["fabricacao", "comercializacao", "distribuicao"], nome_produto: "Hipoclorito de Sódio 1% Solução Desinfetante 1L", fabricante_nome: "HigiLim Química Industrial Ltda", fabricante_cnpj: "90.001.112/0001-01", ementa: "Suspende fabricação, comercialização e distribuição de solução de hipoclorito de sódio 1% por ausência de notificação ANVISA e formulação com substâncias não autorizadas (álcool etílico em associação proibida). RE revogada após regularização.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.479/2021", data_publicacao: "2021-03-09", data_vigencia_inicio: "2021-03-09", status: "vigente", tipo_produto: "saneantes", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Inseticida Doméstico Aerossol para Baratas e Formigas 400ml", fabricante_nome: "PestFree Indústria Química Ltda", fabricante_cnpj: "01.112.223/0001-23", ementa: "Suspende a comercialização e distribuição de inseticida doméstico aerossol por concentração de cipermetrina acima do limite de 0,05% para uso doméstico e ausência de advertências de segurança para crianças e animais domésticos.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.678/2021", data_publicacao: "2021-07-27", data_vigencia_inicio: "2021-07-27", status: "vigente", tipo_produto: "saneantes", tipo_acao: ["comercializacao", "importacao", "distribuicao"], nome_produto: "Desinfetante Multiuso Lavanda Concentrado 2L", fabricante_nome: "CleanPro Importados Ltda", fabricante_cnpj: "12.223.334/0001-45", ementa: "Suspende a comercialização, importação e distribuição de desinfetante multiuso lavanda concentrado por ausência de comprovação de eficácia bactericida/fungicida e rotulagem com alegações de 'elimina 99,9% das bactérias' não comprovadas.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.935/2022", data_publicacao: "2022-04-12", data_vigencia_inicio: "2022-04-12", status: "vigente", tipo_produto: "saneantes", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Raticida Pellet Brodifacum 0,005% para Uso Doméstico 200g", fabricante_nome: "RatControl Saneamento Ambiental Ltda", fabricante_cnpj: "23.334.445/0001-67", ementa: "Suspende a comercialização e distribuição de raticida pellet com brodifacum 0,005% não autorizado para uso doméstico (apenas profissional), com risco de intoxicação acidental em crianças e animais domésticos.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.120/2022", data_publicacao: "2022-09-06", data_vigencia_inicio: "2022-09-06", status: "vigente", tipo_produto: "saneantes", tipo_acao: ["importacao", "comercializacao"], nome_produto: "Água Sanitária Extra Forte 10% Cloro Ativo 1L Importada", fabricante_nome: "SuperClean Importação e Distribuição Ltda", fabricante_cnpj: "34.445.556/0001-89", ementa: "Suspende a importação e comercialização de água sanitária importada com 10% de cloro ativo por ausência de notificação ANVISA e teor de cloro ativo acima do limite de 2,5% permitido para uso doméstico sem prescrição.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.370/2023", data_publicacao: "2023-05-15", data_vigencia_inicio: "2023-05-15", status: "vigente", tipo_produto: "saneantes", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Repelente de Insetos DEET 30% Spray 100ml", fabricante_nome: "SafeGuard Química Ltda", fabricante_cnpj: "45.556.667/0001-01", ementa: "Suspende a comercialização e distribuição de repelente de insetos DEET 30% por concentração acima do limite de 15% para uso em crianças menores de 12 anos indicado na rotulagem, sem as ressalvas obrigatórias de segurança pediátrica.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.956/2024", data_publicacao: "2024-05-06", data_vigencia_inicio: "2024-05-06", status: "vigente", tipo_produto: "saneantes", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Produto para Tratamento de Piscina Cloro Granulado 90% 1kg", fabricante_nome: "AquaPool Química Ltda", fabricante_cnpj: "79.890.123/0001-78", ementa: "Suspende comercialização e distribuição de produto cloro granulado para piscina por ausência de notificação ANVISA, embalagem sem fichas de informação de segurança (FIS) e rotulagem sem instruções de primeiros socorros.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 5.307/2025", data_publicacao: "2025-03-25", data_vigencia_inicio: "2025-03-25", status: "vigente", tipo_produto: "saneantes", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Pastilha Sanitizante para Descarga 50g com Triclosano", fabricante_nome: "Hygienex Brasil Produtos de Limpeza Ltda", fabricante_cnpj: "24.345.678/0001-78", ementa: "Suspende comercialização e distribuição de pastilhas sanitizantes para descarga por teor de triclosano em concentração de 2% (acima do limite de 0,3% para saneantes) e ausência de notificação ANVISA. Produto classificado como uso restrito.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.210/2023", data_publicacao: "2023-02-14", data_vigencia_inicio: "2023-02-14", status: "encerrada", tipo_produto: "saneantes", tipo_acao: ["fabricacao", "comercializacao"], nome_produto: "Sabonete Líquido Antibacteriano Triclosan 0,5% 500ml", fabricante_nome: "SabãoBom Higiene Industrial Ltda", fabricante_cnpj: "90.111.222/0001-33", ementa: "Suspende fabricação e comercialização de sabonete antibacteriano com triclosan 0,5% por concentração acima do permitido para uso doméstico. RE encerrada após substituição do princípio ativo por clorexidina 0,1% e reformulação do produto.", link_documento_oficial: "https://www.in.gov.br/web/dou" },

  // === PRODUTOS PARA SAÚDE ===
  { numero_re: "RE nº 3.155/2020", data_publicacao: "2020-05-05", data_vigencia_inicio: "2020-05-05", status: "revogada", tipo_produto: "produtos_saude", tipo_acao: ["importacao", "comercializacao", "distribuicao"], nome_produto: "Máscara Cirúrgica Descartável Tripla Camada Caixa 50un", fabricante_nome: "MediProt Medical Supplies Co. (importador: ProtéMed Ltda)", fabricante_cnpj: "56.667.778/0001-23", ementa: "Suspende importação, comercialização e distribuição de máscaras cirúrgicas importadas sem registro ANVISA e eficiência de filtragem bacteriana (BFE) abaixo de 95%, durante emergência sanitária COVID-19. RE revogada após fim da emergência.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.308/2020", data_publicacao: "2020-09-01", data_vigencia_inicio: "2020-09-01", status: "revogada", tipo_produto: "produtos_saude", tipo_acao: ["importacao", "comercializacao"], nome_produto: "Oxímetro de Pulso Portátil Sem Fio Modelo OX-100", fabricante_nome: "HealthDevice Tech Co. (importador: MedImport Brasil Ltda)", fabricante_cnpj: "67.778.889/0001-45", ementa: "Suspende importação e comercialização de oxímetros de pulso sem fio por ausência de registro ANVISA e precisão de leitura de SpO2 fora da tolerância de ±2% (erro médio de ±5% identificado em testes laboratoriais).", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.554/2021", data_publicacao: "2021-05-18", data_vigencia_inicio: "2021-05-18", status: "revogada", tipo_produto: "produtos_saude", tipo_acao: ["comercializacao", "distribuicao", "uso"], nome_produto: "Teste Rápido Antígeno COVID-19 (Swab Nasal) Kit 5 Testes", fabricante_nome: "DiagRapid Importação e Distribuidora Ltda", fabricante_cnpj: "78.889.990/0001-67", ementa: "Suspende comercialização, distribuição e uso de kits de teste rápido antígeno COVID-19 por sensibilidade de 62% (abaixo do mínimo de 80% exigido pela ANVISA) identificada em validação pós-mercado. Risco de falsos negativos.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.712/2021", data_publicacao: "2021-09-07", data_vigencia_inicio: "2021-09-07", status: "vigente", tipo_produto: "produtos_saude", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Cateter Venoso Central de Longa Permanência 7Fr", fabricante_nome: "MedLine Industries Inc (representante BR: CathMed Ltda)", fabricante_cnpj: "89.990.001/0001-89", ementa: "Suspende comercialização e distribuição de cateteres venosos centrais de longa permanência 7Fr (lotes específicos) por falha na vedação do hub do cateter identificada em relatório de campo, com risco de embolia gasosa durante inserção.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.867/2022", data_publicacao: "2022-02-22", data_vigencia_inicio: "2022-02-22", status: "vigente", tipo_produto: "produtos_saude", tipo_acao: ["comercializacao", "distribuicao", "uso"], nome_produto: "Prótese de Quadril Total Cimentada Pares M/F", fabricante_nome: "OrthoImplant Brasil Ltda", fabricante_cnpj: "90.001.112/0001-01", ementa: "Suspende comercialização, distribuição e uso de lote de próteses de quadril total cimentadas por não conformidade dimensional na haste femoral (tolerância fora de ±0,05mm), detectada em auditoria de qualidade pelo fabricante.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.021/2022", data_publicacao: "2022-06-14", data_vigencia_inicio: "2022-06-14", status: "vigente", tipo_produto: "produtos_saude", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Stent Coronariano Farmacológico com Everolimus 3,5x28mm", fabricante_nome: "Abbott Vascular Ltda", fabricante_cnpj: "46.781.084/0001-08", ementa: "Suspende comercialização e distribuição de lotes específicos de stent coronariano com everolimus por possível não conformidade na camada de polímero biodegradável que pode afetar a liberação controlada do fármaco.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.158/2022", data_publicacao: "2022-10-03", data_vigencia_inicio: "2022-10-03", status: "vigente", tipo_produto: "produtos_saude", tipo_acao: ["comercializacao", "distribuicao", "uso"], nome_produto: "Seringa de Insulina 1mL com Agulha Integrada 13mm 29G", fabricante_nome: "BD (Becton Dickinson) Industrial Ltda", fabricante_cnpj: "31.590.374/0001-04", ementa: "Suspende comercialização, distribuição e uso de lote de seringas de insulina 1mL com agulha integrada por desvio de qualidade na escala graduada (valores impressos incorretos identificados em 0,5% das unidades do lote).", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.298/2023", data_publicacao: "2023-02-28", data_vigencia_inicio: "2023-02-28", status: "vigente", tipo_produto: "produtos_saude", tipo_acao: ["importacao", "comercializacao"], nome_produto: "Concentrador de Oxigênio Portátil 1-5 LPM Modelo O2Go", fabricante_nome: "OxyCare Medical Devices (importador: RespirarBr Ltda)", fabricante_cnpj: "01.112.223/0001-23", ementa: "Suspende importação e comercialização de concentradores de oxigênio portátil por ausência de registro ANVISA e não conformidade com a norma ABNT NBR IEC 60601-1 (segurança elétrica em equipamentos médicos).", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.430/2023", data_publicacao: "2023-06-27", data_vigencia_inicio: "2023-06-27", status: "vigente", tipo_produto: "produtos_saude", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Desfibrilador Externo Automático (DEA) Modelo DEA-300", fabricante_nome: "Philips Medical Systems (distribuidor: MedEquip Brasil Ltda)", fabricante_cnpj: "12.223.334/0001-45", ementa: "Suspende comercialização e distribuição de DEA modelo DEA-300 (lotes específicos) por falha de software: o dispositivo pode não reconhecer corretamente ritmos fibrilatórios em 0,3% dos casos simulados em teste de campo.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.565/2023", data_publicacao: "2023-09-05", data_vigencia_inicio: "2023-09-05", status: "em_analise", tipo_produto: "produtos_saude", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Marca-passo Cardíaco DDD Dupla Câmara Modelo Endura DR", fabricante_nome: "Biotronik SE & Co. KG (representante: CardioTech BR Ltda)", fabricante_cnpj: "23.334.445/0001-67", ementa: "RE em análise: apuração em curso sobre possíveis interferências eletromagnéticas em marca-passo Endura DR em ambientes com campos magnéticos intensos (IRM de 1,5T). Medida cautelar durante investigação com o fabricante europeu.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.867/2024", data_publicacao: "2024-03-15", data_vigencia_inicio: "2024-03-15", status: "vigente", tipo_produto: "produtos_saude", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Glicosímetro e Tiras Reagentes Modelo GlucoFast Slim", fabricante_nome: "InfoLab Diagnósticos Ltda", fabricante_cnpj: "57.678.901/0001-34", ementa: "Suspende comercialização e distribuição de sistema glicosímetro+tiras GlucoFast Slim por desvio de exatidão médio de ±18% (limite ISO 15197:2013: ±15% para valores >100mg/dL), podendo levar a decisões terapêuticas inadequadas.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 5.087/2024", data_publicacao: "2024-09-03", data_vigencia_inicio: "2024-09-03", status: "vigente", tipo_produto: "produtos_saude", tipo_acao: ["importacao", "comercializacao", "distribuicao"], nome_produto: "Agulha de Acupuntura Descartável 0,25x25mm Caixa 100un", fabricante_nome: "Suzhou Acupuncture Devices Co. (importador: OrientalMed Ltda)", fabricante_cnpj: "91.012.345/0001-12", ementa: "Suspende importação, comercialização e distribuição de agulhas de acupuntura importadas por ausência de registro ANVISA como dispositivo médico invasivo e não conformidade com ABNT NBR 15363 (revestimento de silicone inadequado).", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.620/2023", data_publicacao: "2023-10-03", data_vigencia_inicio: "2023-10-03", status: "vigente", tipo_produto: "produtos_saude", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Implante de Silicone para Mama Gel Cohesivo Alta Projeção 300cc", fabricante_nome: "Allergan Produtos Farmacêuticos Ltda", fabricante_cnpj: "60.932.366/0001-82", ementa: "Suspende comercialização e distribuição de lotes específicos de implantes mamários de gel coesivo por notificação internacional (FDA, Health Canada) sobre possível associação com linfoma anaplásico de grandes células (BIA-ALCL). Investigação epidemiológica em andamento.", link_documento_oficial: "https://www.in.gov.br/web/dou" },

  // === INSUMOS FARMACÊUTICOS ===
  { numero_re: "RE nº 3.166/2020", data_publicacao: "2020-05-20", data_vigencia_inicio: "2020-05-20", status: "revogada", tipo_produto: "insumos_farmaceuticos", tipo_acao: ["importacao", "uso"], nome_produto: "Estearato de Magnésio Vegetal Grau Farmacêutico 25kg", principio_ativo: "Estearato de magnésio", fabricante_nome: "Baerlocher GmbH (importador: QuimiFarma Ltda)", fabricante_cnpj: "34.445.556/0001-89", ementa: "Suspende importação e uso de lote de estearato de magnésio vegetal grau farmacêutico por contaminação com metais pesados (cádmio 0,8 ppm; limite USP <232>: 0,5 ppm). RE revogada após destruição do lote.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.423/2021", data_publicacao: "2021-02-02", data_vigencia_inicio: "2021-02-02", status: "vigente", tipo_produto: "insumos_farmaceuticos", tipo_acao: ["importacao", "uso", "distribuicao"], nome_produto: "Celulose Microcristalina PH-102 Grau Farmacêutico 25kg", principio_ativo: "Celulose microcristalina", fabricante_nome: "FMC Corporation (importador: IngredFarma Distribuidora Ltda)", fabricante_cnpj: "45.556.667/0001-01", ementa: "Suspende importação, uso e distribuição de lote de celulose microcristalina PH-102 por não conformidade nos parâmetros de fluxo e compressibilidade (índice de Carr > 25%), comprometendo a produção de comprimidos de dissolução controlada.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.844/2022", data_publicacao: "2022-01-11", data_vigencia_inicio: "2022-01-11", status: "vigente", tipo_produto: "insumos_farmaceuticos", tipo_acao: ["importacao", "distribuicao", "uso"], nome_produto: "Gelatina Farmacêutica 150 Bloom Tipo A Suíno 25kg", principio_ativo: "Gelatina", fabricante_nome: "Gelita AG (importador: GelFarma Brasil Ltda)", fabricante_cnpj: "67.778.889/0001-45", ementa: "Suspende importação, distribuição e uso de lote de gelatina farmacêutica tipo A suíno por suspeita de adulteração com gelatina bovina não declarada e ausência de rastreabilidade do material de origem animal.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.012/2022", data_publicacao: "2022-06-21", data_vigencia_inicio: "2022-06-21", status: "vigente", tipo_produto: "insumos_farmaceuticos", tipo_acao: ["importacao", "uso"], nome_produto: "Lactose Mono-hidratada 200M Grau Farmacêutico 25kg", principio_ativo: "Lactose mono-hidratada", fabricante_nome: "DFE Pharma GmbH & Co. KG (importador: ExcipiPharma Ltda)", fabricante_cnpj: "78.889.990/0001-67", ementa: "Suspende importação e uso de lote de lactose mono-hidratada grau farmacêutico por nível de proteína do leite residual potencialmente alergênico e ausência de declaração adequada de alérgeno no certificado de análise do fabricante.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 5.178/2024", data_publicacao: "2024-11-20", data_vigencia_inicio: "2024-11-20", status: "vigente", tipo_produto: "insumos_farmaceuticos", tipo_acao: ["importacao", "distribuicao", "uso"], nome_produto: "Polissorbato 80 Grau Farmacêutico (Tween 80) 210kg", principio_ativo: "Polissorbato 80", fabricante_nome: "Croda International Plc (importador: EmulsFarma Ltda)", fabricante_cnpj: "13.234.567/0001-56", ementa: "Suspende importação, distribuição e uso de lote de polissorbato 80 grau farmacêutico por contaminação com 1,4-dioxano em concentração de 18 ppm (limite EMA: ≤10 ppm), substância potencialmente carcinogênica de classe 2B (IARC).", link_documento_oficial: "https://www.in.gov.br/web/dou" },

  // === FÁRMACOS / API ===
  { numero_re: "RE nº 3.233/2020", data_publicacao: "2020-07-08", data_vigencia_inicio: "2020-07-08", status: "revogada", tipo_produto: "farmacos", tipo_acao: ["importacao", "fabricacao"], nome_produto: "Losartana Potássica API Granel 99% (DCF)", principio_ativo: "Losartana potássica", fabricante_nome: "Huahai Pharmaceuticals Co. Ltd (China)", ementa: "Suspende importação e fabricação com losartana potássica API granel proveniente da Huahai Pharmaceuticals por detecção de NDMA acima do limite de 0,32 ppm, em alinhamento com recall global coordenado por FDA e EMA. RE revogada após substituição de fornecedor.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.688/2021", data_publicacao: "2021-08-24", data_vigencia_inicio: "2021-08-24", status: "vigente", tipo_produto: "farmacos", tipo_acao: ["importacao", "uso"], nome_produto: "Ranitidina Cloridrato API Granel 98,5%", principio_ativo: "Ranitidina cloridrato", fabricante_nome: "Vários fabricantes de API", ementa: "Suspende importação e uso da ranitidina cloridrato API granel por formação endógena de NDMA (N-nitrosodimetilamina) acima de 96 ng/dia, em decorrência de instabilidade intrínseca da molécula. Decisão em linha com cancelamento global coordenado por FDA.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.911/2022", data_publicacao: "2022-03-22", data_vigencia_inicio: "2022-03-22", status: "vigente", tipo_produto: "farmacos", tipo_acao: ["importacao", "fabricacao", "distribuicao"], nome_produto: "Cloridrato de Pioglitazona API 99% (DCF)", principio_ativo: "Pioglitazona", fabricante_nome: "Aurobindo Pharma Ltd (importador: FarmaAPI Distribuidora Ltda)", fabricante_cnpj: "90.001.112/0001-01", ementa: "Suspende importação, fabricação e distribuição de lote de pioglitazona API por impureza de processo desconhecida em concentração de 0,3% não identificada no certificado de análise, exigindo investigação e qualificação conforme ICH Q3A.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.145/2022", data_publicacao: "2022-09-27", data_vigencia_inicio: "2022-09-27", status: "vigente", tipo_produto: "farmacos", tipo_acao: ["importacao", "uso"], nome_produto: "Canabidiol (CBD) API Matéria-Prima 99% HPLC", principio_ativo: "Canabidiol", fabricante_nome: "Trigal Pharma S.A. (importador: CannaBrasil API Ltda)", fabricante_cnpj: "01.112.223/0001-23", ementa: "Suspende importação e uso de lote de CBD API por razão CBD:THC inferior a 50:1 (encontrada 42:1), resultado fora do limite estabelecido pela RDC nº 327/2019, e ausência de autorização ANVISA para importação de substância controlada.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 5.042/2024", data_publicacao: "2024-07-30", data_vigencia_inicio: "2024-07-30", status: "vigente", tipo_produto: "farmacos", tipo_acao: ["importacao", "fabricacao"], nome_produto: "Tirzepatida API Granel Peptídeo Sintético (DCF)", principio_ativo: "Tirzepatida", fabricante_nome: "PolyPeptide Group AB (importador: PeptideFarma Ltda)", fabricante_cnpj: "80.901.234/0001-90", ementa: "Suspende importação e fabricação com tirzepatida API por impureza de sequência incorreta (Asp10 ao invés de Glu10) em concentração de 0,15%, acima do limite qualificado de 0,1%, detectada em análise por espectrometria de massa LC-MS/MS.", link_documento_oficial: "https://www.in.gov.br/web/dou" },

  // === CANNABIS ===
  { numero_re: "RE nº 3.730/2021", data_publicacao: "2021-10-05", data_vigencia_inicio: "2021-10-05", status: "vigente", tipo_produto: "cannabis", tipo_acao: ["importacao", "comercializacao"], nome_produto: "Full Spectrum CBD Oil 3000mg 30ml", principio_ativo: "Canabidiol (CBD); Canabinoides totais", fabricante_nome: "Charlotte's Web Holdings Inc (importador: CannaImport BR Ltda)", fabricante_cnpj: "12.223.334/0001-45", ementa: "Suspende importação e comercialização de óleo CBD full spectrum 3000mg por ausência de autorização de importação específica da ANVISA e teor de THC total de 0,4% acima do limite máximo de 0,2% para produtos de cannabis autorizada.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.888/2022", data_publicacao: "2022-02-15", data_vigencia_inicio: "2022-02-15", status: "vigente", tipo_produto: "cannabis", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Canabidiol 200mg/mL Solução Oral Manipulada 30mL", principio_ativo: "Canabidiol", fabricante_nome: "Farmácia de Manipulação Natural Ltda", fabricante_cnpj: "23.334.445/0001-67", ementa: "Suspende comercialização e distribuição de canabidiol 200mg/mL manipulado por ausência de BPF (Boas Práticas de Fabricação) para cannabis medicinal e uso de API sem certificação do fornecedor conforme RDC nº 660/2022.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.243/2023", data_publicacao: "2023-02-07", data_vigencia_inicio: "2023-02-07", status: "vigente", tipo_produto: "cannabis", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Cápsulas Softgel CBD Isolado 25mg 30 cápsulas", principio_ativo: "Canabidiol isolado", fabricante_nome: "VerdeMed Produtos Naturais Ltda", fabricante_cnpj: "45.556.667/0001-01", ementa: "Suspende comercialização e distribuição de cápsulas de CBD isolado 25mg por rotulagem com indicações terapêuticas não autorizadas (tratamento de ansiedade, insônia e depressão) sem comprovação de eficácia clínica e sem registro como medicamento.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.395/2023", data_publicacao: "2023-05-29", data_vigencia_inicio: "2023-05-29", status: "em_analise", tipo_produto: "cannabis", tipo_acao: ["importacao", "comercializacao"], nome_produto: "Nabiximols (Sativex) 27mg/mL + 25mg/mL Spray Bucal 5,5mL", principio_ativo: "Extrato de Cannabis sativa (THC + CBD)", fabricante_nome: "GW Pharmaceuticals Plc (importador: NabiMed Ltda)", fabricante_cnpj: "56.667.778/0001-23", ementa: "RE em análise: apuração em curso sobre importação não autorizada de Sativex spray bucal por canal não oficial. Produto identificado no mercado sem autorização de importação individual válida emitida pela ANVISA.", link_documento_oficial: "https://www.in.gov.br/web/dou" },

  // === DROGA VEGETAL ===
  { numero_re: "RE nº 3.350/2020", data_publicacao: "2020-11-10", data_vigencia_inicio: "2020-11-10", status: "revogada", tipo_produto: "droga_vegetal", tipo_acao: ["comercializacao", "importacao"], nome_produto: "Erva-de-São-João (Hypericum perforatum) Extrato Seco 300mg Cápsulas", principio_ativo: "Hipericina (0,3%); Hiperforina (3-6%)", fabricante_nome: "HerbNatura Indústria Fitoterápica Ltda", fabricante_cnpj: "67.778.889/0001-45", ementa: "Suspende comercialização e importação de erva-de-São-João 300mg por teor de hipericina abaixo do especificado (encontrado 0,07%; mínimo 0,3% conforme registro) e alegações de ação antidepressiva não autorizadas para fitoterápico.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.527/2021", data_publicacao: "2021-05-04", data_vigencia_inicio: "2021-05-04", status: "vigente", tipo_produto: "droga_vegetal", tipo_acao: ["importacao", "comercializacao", "distribuicao"], nome_produto: "Raiz de Ashwagandha (Withania somnifera) em Pó 500g Granel", principio_ativo: "Withanolídeos totais", fabricante_nome: "India Herbs Export Pvt Ltd (importador: HerbImport BR Ltda)", fabricante_cnpj: "78.889.990/0001-67", ementa: "Suspende importação, comercialização e distribuição de ashwagandha em pó a granel por ausência de cadastro na ANVISA como droga vegetal e contaminação por metais pesados (chumbo 4,2 ppm) próximo ao limite.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.703/2021", data_publicacao: "2021-09-21", data_vigencia_inicio: "2021-09-21", status: "vigente", tipo_produto: "droga_vegetal", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Folhas de Boldo-do-Chile Dessecadas Granel 100g", principio_ativo: "Boldina (alcaloide principal)", fabricante_nome: "Empório das Ervas Comércio Ltda", fabricante_cnpj: "89.990.001/0001-89", ementa: "Suspende comercialização e distribuição de boldo-do-Chile dessecado a granel por identificação de adulteração com Plectranthus barbatus (boldo brasileiro) em proporção de 60%, produto diferente com outro perfil fitoquímico e segurança.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.007/2022", data_publicacao: "2022-06-07", data_vigencia_inicio: "2022-06-07", status: "vigente", tipo_produto: "droga_vegetal", tipo_acao: ["importacao", "comercializacao"], nome_produto: "Cogumelo Reishi (Ganoderma lucidum) Extrato 10:1 500mg Cápsulas", principio_ativo: "Polissacarídeos beta-glucanos; Triterpenos ganodéricos", fabricante_nome: "Fungi Health International (importador: Coguvida BR Ltda)", fabricante_cnpj: "90.001.112/0001-01", ementa: "Suspende importação e comercialização de extrato de reishi 10:1 por alegações terapêuticas de imunomodulação e anticarcinogênese não autorizadas, ausência de notificação ANVISA e adulteração com amido de milho não declarado.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.175/2022", data_publicacao: "2022-10-13", data_vigencia_inicio: "2022-10-13", status: "vigente", tipo_produto: "droga_vegetal", tipo_acao: ["comercializacao", "distribuicao"], nome_produto: "Passiflora (Passiflora incarnata) Tintura Mãe 1:10 50mL", principio_ativo: "Flavonoides totais expressos em vitexina", fabricante_nome: "Florais e Tinturas do Brasil Ltda", fabricante_cnpj: "01.112.223/0001-23", ementa: "Suspende comercialização e distribuição de tintura mãe de passiflora por teor de flavonoides abaixo do mínimo farmacopeico (encontrado 0,004%; mínimo FB 6ª Ed.: 0,01%) e contaminação por pesticida carbendazim acima do LMR.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.630/2023", data_publicacao: "2023-10-17", data_vigencia_inicio: "2023-10-17", status: "vigente", tipo_produto: "droga_vegetal", tipo_acao: ["importacao", "comercializacao", "distribuicao"], nome_produto: "Extrato Seco de Cúrcuma (Curcuma longa) 500mg 95% Curcuminoides Cápsulas", principio_ativo: "Curcuminoides totais (curcumina, demetoxicurcumina, bisdemetoxicurcumina)", fabricante_nome: "Sabinsa Corporation (importador: CurcumaBR Ltda)", fabricante_cnpj: "14.345.678/0001-89", ementa: "Suspende importação, comercialização e distribuição de extrato de cúrcuma por teor de chumbo de 3,1 ppm (acima do limite RDC nº 222/2006 para drogas vegetais: 3,0 ppm) e uso de solventes residuais não declarados na extração.", link_documento_oficial: "https://www.in.gov.br/web/dou" },

  // === SUBSTÂNCIAS ATIVAS / ESTÉTICA ===
  { numero_re: "RE nº 3.558/2021", data_publicacao: "2021-06-01", data_vigencia_inicio: "2021-06-01", status: "vigente", tipo_produto: "substancias_ativas", tipo_acao: ["importacao", "distribuicao", "uso"], nome_produto: "Ácido Hialurônico Reticulado para Preenchimento Dérmico 1mL", principio_ativo: "Ácido hialurônico sódico reticulado (BDDE)", fabricante_nome: "Q-Med AB (Galderma) (distribuidor: FillArt Medical Ltda)", fabricante_cnpj: "12.223.334/0001-45", ementa: "Suspende importação, distribuição e uso de lote de ácido hialurônico reticulado para preenchimento dérmico por não conformidade no teste de esterilidade (presença de endotoxinas bacterianas acima de 0,5 EU/mL).", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 3.790/2022", data_publicacao: "2022-01-04", data_vigencia_inicio: "2022-01-04", status: "vigente", tipo_produto: "substancias_ativas", tipo_acao: ["importacao", "comercializacao", "distribuicao"], nome_produto: "Toxina Botulínica Tipo A 100 UI Liofilizada (BTX-A)", principio_ativo: "Toxina botulínica tipo A (complexo hemaglutinico)", fabricante_nome: "Allergan Produtos Farmacêuticos Ltda", fabricante_cnpj: "60.932.366/0001-82", ementa: "Suspende importação, comercialização e distribuição de lotes específicos de toxina botulínica tipo A 100 UI por falha na cadeia de frio identificada durante transporte (exposição a temperatura de -10°C por >4h, comprometendo a estabilidade).", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.183/2022", data_publicacao: "2022-10-25", data_vigencia_inicio: "2022-10-25", status: "vigente", tipo_produto: "substancias_ativas", tipo_acao: ["importacao", "comercializacao", "distribuicao"], nome_produto: "Hidroxiapatita de Cálcio para Bioestimulação 1,5mL Seringa", principio_ativo: "Hidroxiapatita de cálcio 30% em gel carboximetilcelulose", fabricante_nome: "Merz Pharma GmbH & Co. KGaA (importador: MerzBrasil Ltda)", fabricante_cnpj: "34.445.556/0001-89", ementa: "Suspende importação, comercialização e distribuição de lotes de hidroxiapatita de cálcio 1,5mL por não conformidade na concentração de CaHA encontrada em 27,8% vs. especificado 30% ±2%, abaixo do limite inferior.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
  { numero_re: "RE nº 4.520/2023", data_publicacao: "2023-07-18", data_vigencia_inicio: "2023-07-18", status: "vigente", tipo_produto: "substancias_ativas", tipo_acao: ["importacao", "uso", "distribuicao"], nome_produto: "Fio de PDO (Polidioxanona) Absorbível para Lifting Facial 19G 90mm", principio_ativo: "Polidioxanona (PDO)", fabricante_nome: "HansBiomed Corp. (importador: FiloCirurgico Ltda)", fabricante_cnpj: "25.456.789/0001-01", ementa: "Suspende importação, uso e distribuição de fios de PDO para lifting facial por ausência de registro ANVISA como dispositivo médico implantável e ausência de dados de biodegradação em prazo declarado de 6 meses.", link_documento_oficial: "https://www.in.gov.br/web/dou" },
] as const;

async function main() {
  console.log(`Seeding ${resolucoes.length} REs...`);

  let inserted = 0;
  let skipped = 0;

  for (const re of resolucoes) {
    try {
      await sql`
        INSERT INTO resolucoes_especificas (
          numero_re, data_publicacao, data_vigencia_inicio, status,
          tipo_produto, tipo_acao, nome_produto, principio_ativo,
          fabricante_nome, fabricante_cnpj, numero_registro_anvisa,
          ementa, link_documento_oficial
        ) VALUES (
          ${re.numero_re},
          ${re.data_publicacao},
          ${re.data_vigencia_inicio},
          ${re.status},
          ${re.tipo_produto},
          ${re.tipo_acao as string[]},
          ${re.nome_produto},
          ${"principio_ativo" in re ? re.principio_ativo ?? null : null},
          ${"fabricante_nome" in re ? re.fabricante_nome ?? null : null},
          ${"fabricante_cnpj" in re ? re.fabricante_cnpj ?? null : null},
          ${"numero_registro_anvisa" in re ? re.numero_registro_anvisa ?? null : null},
          ${re.ementa},
          ${"link_documento_oficial" in re ? re.link_documento_oficial ?? null : null}
        )
        ON CONFLICT (numero_re) DO NOTHING
      `;
      inserted++;
    } catch (err) {
      console.error(`  SKIP ${re.numero_re}:`, (err as Error).message);
      skipped++;
    }
  }

  const [{ count }] = await sql<[{ count: string }]>`SELECT COUNT(*) as count FROM resolucoes_especificas WHERE deleted_at IS NULL`;
  console.log(`Done. Inserted: ${inserted} | Skipped (conflict): ${skipped} | Total in DB: ${count}`);
  await sql.end();
}

main().catch(console.error);
